name: Execute gRPC Command

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  grpc-command:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Install gRPC tools (e.g., grpcurl)
    - name: Install grpcurl
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -L https://github.com/fullstorydev/grpcurl/releases/latest/download/grpcurl-linux-x86_64 -o /usr/local/bin/grpcurl
        chmod +x /usr/local/bin/grpcurl

    # Step 3: Run the gRPC command
    - name: Execute gRPC Command
      run: |
        grpcurl -plaintext -d '{"name": "World"}' localhost:50051 helloworld.Greeter/SayHello

