name: Deploying Otel via ArgoCD

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      cluster_context:
        description: "Provide the context"
        required: true
        default: "default"     

jobs:
  App-argocd:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    #Step 2 Setting the cluster to deploy helm
    - name: Setting the context  
      run: |
         kubectl config use-context ${{ inputs.cluster_context }}
         kubectl config current-context
         kubectl apply -f argo-app/my-helm-app.yaml

