name: Creating a k8s secret

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      secret_for_cluster:
        description: "Provide the key"
        required: true
        default: "default"   

jobs:
  grpc-command:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
    #Step 2 Setting the cluster to deploy helm
    - name: Setting the context  
      run: |
         kubectl config use-context ashish-test@ashish-cluster-test.ap-south-1.eksctl.io
         kubectl config current-context

    - name: Display passed variable
      run: |
        echo "The passed variable is: ${{ inputs.secret_for_cluster}}"     
         
    # Step 3: Creating secret
    - name: Creating secret
      run: |
        SEC_VARIABLE=${{ inputs.secret_for_cluster }}
        kubectl create secret generic coralogix-opentelemetry-key-first --from-literal=PRIVATE_KEY="$SEC_VARIABLE"

