name: Creating a k8s secret

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      secret_for_cluster:
        description: "Provide the key"
        required: true
        default: "default"   
      cluster_context:
        description: "Provide the context"
        required: true
        default: "default"        

jobs:
  Secret-creation:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
    #Step 2 Setting the cluster to deploy helm
    - name: Setting the context  
      run: |
         kubectl config use-context ${{ inputs.cluster_context }}
         kubectl config current-context
         
    # Step 3: Creating secret
    - name: Creating secret
      run: |
        SEC_VARIABLE=${{ inputs.secret_for_cluster }}
        kubectl create secret generic coralogix-opentelemetry-key-second --from-literal=PRIVATE_KEY="$SEC_VARIABLE"

