name: Execute gRPC Command



on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main

jobs:
  grpc-command:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
    #Step 2 Setting the cluster to deploy helm
    - name: Setting the context  
      run: |
         kubectl config use-context ashish-test@ashish-cluster-test.ap-south-1.eksctl.io
         kubectl config current-context
         

    # Step 3: Creating secret
    - name: Execute gRPC Command
      run: |
        kubectl create secret generic coralogix-opentelemetry-key-test --from-literal=PRIVATE_KEY="cxtp_dLRA3MmuEDo4vaWAGj6OsdCGKhdtb9"

