name: Sync the app with cluster

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      argo_app_name:
        description: "Provide the app name"
        required: true
        default: "default"   

jobs:
  grpc-command:
    runs-on: self-hosted  
    
    steps:     
    # Step 1: Sync app
    - name: sync-app
      run: | 
         argocd app sync ${{ inputs.argo_app_name }}

